
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32537 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.36.32537.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        D:/Luki/Domace vyucovanie/FRI UNIZA/Bc/3. Rocnik/zimny/POS/Semestralna praca/POSGameOfLifeClient/cmake-build-debug_win/CMakeFiles/3.26.4/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        Note: including file: D:\\Luki\\Domace vyucovanie\\FRI UNIZA\\Bc\\3. Rocnik\\zimny\\POS\\Semestralna praca\\POSGameOfLifeClient\\cmake-build-debug_win\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32537 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.36.32537.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        D:/Luki/Domace vyucovanie/FRI UNIZA/Bc/3. Rocnik/zimny/POS/Semestralna praca/POSGameOfLifeClient/cmake-build-debug_win/CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        Note: including file: D:\\Luki\\Domace vyucovanie\\FRI UNIZA\\Bc\\3. Rocnik\\zimny\\POS\\Semestralna praca\\POSGameOfLifeClient\\cmake-build-debug_win\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/Luki/Domace vyucovanie/FRI UNIZA/Bc/3. Rocnik/zimny/POS/Semestralna praca/POSGameOfLifeClient/cmake-build-debug_win/CMakeFiles/CMakeScratch/TryCompile-sfha8d"
      binary: "D:/Luki/Domace vyucovanie/FRI UNIZA/Bc/3. Rocnik/zimny/POS/Semestralna praca/POSGameOfLifeClient/cmake-build-debug_win/CMakeFiles/CMakeScratch/TryCompile-sfha8d"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: D:/Luki/Domace vyucovanie/FRI UNIZA/Bc/3. Rocnik/zimny/POS/Semestralna praca/POSGameOfLifeClient/cmake-build-debug_win/CMakeFiles/CMakeScratch/TryCompile-sfha8d
        
        Run Build Command(s):C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_8936f\\fast && 	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_8936f.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_8936f.dir\\build
        Building C object CMakeFiles/cmTC_8936f.dir/CMakeCCompilerABI.c.obj
        	"C:\\Program Files\\JetBrains\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_8936f.dir\\CMakeCCompilerABI.c.obj.d --working-dir="D:\\Luki\\Domace vyucovanie\\FRI UNIZA\\Bc\\3. Rocnik\\zimny\\POS\\Semestralna praca\\POSGameOfLifeClient\\cmake-build-debug_win\\CMakeFiles\\CMakeScratch\\TryCompile-sfha8d" --filter-prefix="Note: including file: " -- C:\\PROGRA~1\\MICROS~3\\2022\\ENTERP~1\\VC\\Tools\\MSVC\\1436~1.325\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\Tatry\\AppData\\Local\\Temp\\nmFB02.tmp
        CMakeCCompilerABI.c
        Linking C executable cmTC_8936f.exe
        	"C:\\Program Files\\JetBrains\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_8936f.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe --manifests -- C:\\PROGRA~1\\MICROS~3\\2022\\ENTERP~1\\VC\\Tools\\MSVC\\1436~1.325\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_8936f.dir\\objects1.rsp @C:\\Users\\Tatry\\AppData\\Local\\Temp\\nmFCA9.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_8936f.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_8936f.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_8936f.dir/manifest.res CMakeFiles\\cmTC_8936f.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~1\\MICROS~3\\2022\\ENTERP~1\\VC\\Tools\\MSVC\\1436~1.325\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_8936f.dir\\objects1.rsp /out:cmTC_8936f.exe /implib:cmTC_8936f.lib /pdb:D:\\Luki\\Domace vyucovanie\\FRI UNIZA\\Bc\\3. Rocnik\\zimny\\POS\\Semestralna praca\\POSGameOfLifeClient\\cmake-build-debug_win\\CMakeFiles\\CMakeScratch\\TryCompile-sfha8d\\cmTC_8936f.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_8936f.dir/intermediate.manifest CMakeFiles\\cmTC_8936f.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_8936f.dir/intermediate.manifest /out:CMakeFiles\\cmTC_8936f.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_8936f.dir/manifest.res CMakeFiles\\cmTC_8936f.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~1\\MICROS~3\\2022\\ENTERP~1\\VC\\Tools\\MSVC\\1436~1.325\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_8936f.dir\\objects1.rsp /out:cmTC_8936f.exe /implib:cmTC_8936f.lib /pdb:D:\\Luki\\Domace vyucovanie\\FRI UNIZA\\Bc\\3. Rocnik\\zimny\\POS\\Semestralna praca\\POSGameOfLifeClient\\cmake-build-debug_win\\CMakeFiles\\CMakeScratch\\TryCompile-sfha8d\\cmTC_8936f.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_8936f.dir/intermediate.manifest CMakeFiles\\cmTC_8936f.dir/manifest.res
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/Luki/Domace vyucovanie/FRI UNIZA/Bc/3. Rocnik/zimny/POS/Semestralna praca/POSGameOfLifeClient/cmake-build-debug_win/CMakeFiles/CMakeScratch/TryCompile-mmiczj"
      binary: "D:/Luki/Domace vyucovanie/FRI UNIZA/Bc/3. Rocnik/zimny/POS/Semestralna praca/POSGameOfLifeClient/cmake-build-debug_win/CMakeFiles/CMakeScratch/TryCompile-mmiczj"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: D:/Luki/Domace vyucovanie/FRI UNIZA/Bc/3. Rocnik/zimny/POS/Semestralna praca/POSGameOfLifeClient/cmake-build-debug_win/CMakeFiles/CMakeScratch/TryCompile-mmiczj
        
        Run Build Command(s):C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_f73dd\\fast && 	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_f73dd.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_f73dd.dir\\build
        Building CXX object CMakeFiles/cmTC_f73dd.dir/CMakeCXXCompilerABI.cpp.obj
        	"C:\\Program Files\\JetBrains\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_f73dd.dir\\CMakeCXXCompilerABI.cpp.obj.d --working-dir="D:\\Luki\\Domace vyucovanie\\FRI UNIZA\\Bc\\3. Rocnik\\zimny\\POS\\Semestralna praca\\POSGameOfLifeClient\\cmake-build-debug_win\\CMakeFiles\\CMakeScratch\\TryCompile-mmiczj" --filter-prefix="Note: including file: " -- C:\\PROGRA~1\\MICROS~3\\2022\\ENTERP~1\\VC\\Tools\\MSVC\\1436~1.325\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\Tatry\\AppData\\Local\\Temp\\nmFF28.tmp
        CMakeCXXCompilerABI.cpp
        Linking CXX executable cmTC_f73dd.exe
        	"C:\\Program Files\\JetBrains\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_f73dd.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe --manifests -- C:\\PROGRA~1\\MICROS~3\\2022\\ENTERP~1\\VC\\Tools\\MSVC\\1436~1.325\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_f73dd.dir\\objects1.rsp @C:\\Users\\Tatry\\AppData\\Local\\Temp\\nmFFA6.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_f73dd.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_f73dd.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_f73dd.dir/manifest.res CMakeFiles\\cmTC_f73dd.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~1\\MICROS~3\\2022\\ENTERP~1\\VC\\Tools\\MSVC\\1436~1.325\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_f73dd.dir\\objects1.rsp /out:cmTC_f73dd.exe /implib:cmTC_f73dd.lib /pdb:D:\\Luki\\Domace vyucovanie\\FRI UNIZA\\Bc\\3. Rocnik\\zimny\\POS\\Semestralna praca\\POSGameOfLifeClient\\cmake-build-debug_win\\CMakeFiles\\CMakeScratch\\TryCompile-mmiczj\\cmTC_f73dd.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_f73dd.dir/intermediate.manifest CMakeFiles\\cmTC_f73dd.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_f73dd.dir/intermediate.manifest /out:CMakeFiles\\cmTC_f73dd.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_f73dd.dir/manifest.res CMakeFiles\\cmTC_f73dd.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~1\\MICROS~3\\2022\\ENTERP~1\\VC\\Tools\\MSVC\\1436~1.325\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_f73dd.dir\\objects1.rsp /out:cmTC_f73dd.exe /implib:cmTC_f73dd.lib /pdb:D:\\Luki\\Domace vyucovanie\\FRI UNIZA\\Bc\\3. Rocnik\\zimny\\POS\\Semestralna praca\\POSGameOfLifeClient\\cmake-build-debug_win\\CMakeFiles\\CMakeScratch\\TryCompile-mmiczj\\cmTC_f73dd.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_f73dd.dir/intermediate.manifest CMakeFiles\\cmTC_f73dd.dir/manifest.res
        
      exitCode: 0
...
